spring.application.name=habit-tracker

# База данных
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/habit_tracker}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
logging.level.liquibase=DEBUG

# JWT
jwt.secret=${JWT_SECRET:default-secret-for-local-dev-only}
jwt.expiration=${JWT_EXPIRATION:86400000}