spring.application.name=habit-tracker
spring.datasource.url=jdbc:postgresql://localhost:5434/habit_tracker
spring.datasource.username=habitUser
spring.datasource.password=habitPassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
logging.level.liquibase=DEBUG